Repository bp-momentum/backend, pull requests merged in 2022-03, with the labels that each got.

#108 fix: typo
  BPBackendDjango/BPBackendDjango/Views/userviews.py
  BPBackendDjango/BPBackendDjango/testing.py
  BPBackendDjango/BPBackendDjango/urls.py
Labels: bug

#109 fix: trainer contact
  BPBackendDjango/BPBackendDjango/Views/userviews.py
Labels: enhancement

#112 feat: Show Full name when trainer requests leaderboard
  .github/workflows/test.yml
  BPBackendDjango/BPBackendDjango/Views/leaderboardviews.py
Labels: enhancement

#97 feat: reset password with email
  BPBackendDjango/BPBackendDjango/Helperclasses/jwttoken.py
  BPBackendDjango/BPBackendDjango/Views/userviews.py
  BPBackendDjango/BPBackendDjango/templates/BPBackendDjango/resetEmail.html
  BPBackendDjango/BPBackendDjango/testing.py
  BPBackendDjango/BPBackendDjango/urls.py
Labels: enhancement

#125 fix: get done exercises
  BPBackendDjango/BPBackendDjango/Views/exerciseviews.py
Labels: bug, prio high

#126 fix: streak
  BPBackendDjango/BPBackendDjango/consumers.py
Labels: bug, prio high

#128 fix: get done post
  BPBackendDjango/BPBackendDjango/Views/exerciseviews.py
Labels: bug, prio high

#129 fix:default language
  BPBackendDjango/BPBackendDjango/models.py
  BPBackendDjango/BPBackendDjango/testing.py
Labels: prio high

#130 fix: done this week
  BPBackendDjango/BPBackendDjango/Views/exerciseviews.py
Labels: bug, prio high

#131 fix: point get now updated
  BPBackendDjango/BPBackendDjango/consumers.py
Labels: prio high

#133 fix: point get now updated
  BPBackendDjango/BPBackendDjango/consumers.py
Labels: bug

#134 fix: urls
  BPBackendDjango/BPBackendDjango/urls.py
Labels: prio high

#136 new
  BPBackendDjango/BPBackendDjango/Helperclasses/ai.py
  BPBackendDjango/BPBackendDjango/consumers.py
Labels: prio high

#135 fix: remove pdf
  BP.pdf
Labels: bug

#139 feat: Settings
  BPBackendDjango/BPBackendDjango/Helperclasses/handlers.py
  BPBackendDjango/BPBackendDjango/settings.py
Labels: enhancement

#141 fix: fixed streaks [start]
  BPBackendDjango/BPBackendDjango/Helperclasses/handlers.py
Labels: bug
